// lib/health.mjs — 每台机器的体检报告（**随同步流动**，于是远程机器可见）。
//
// 解决什么问题：插件在两台机器上跑，但我（或你）只能坐在一台前面。如果
// Windows 那边出错，本机日志看不到。所以每台机器把自己的健康快照写成
// `omnisync-devices/<deviceId>.json` 并推上云 —— 拉一次就能看到对面怎么了。
//
// 隐私边界：只报**结构性事实**（版本/平台/计数/错误码），不报文件内容、
// 不报用户名与绝对路径。仓库是私有的，但仍按最小必要原则。

/** 报告 schema 版本（与字段同进同退；内部常量，报告里以 reportV 出现）。 */
const REPORT_VERSION = 1

/**
 * 生成体检报告。
 * @param {object} input - { deviceId, version, state, cfg, gitVersion, counts, sessions }。
 * @returns {object} 可直接序列化的报告。
 */
export function buildReport(input) {
  const s = input.state ?? {}
  return {
    reportV: REPORT_VERSION,
    at: input.now ?? Date.now(),
    deviceId: input.deviceId ?? 'unknown',
    // 运行环境（跨平台问题第一现场）
    platform: process.platform,
    arch: process.arch,
    node: process.versions.node,
    electron: process.versions.electron ?? null,
    version: input.version ?? 'unknown',
    // 同步健康度
    state: s.lastError === null || s.lastError === undefined ? 'ok' : 'error',
    lastError: s.lastError ?? null,
    lastSyncedAt: s.lastSyncedAt ?? 0,
    backoffUntil: s.backoffUntil ?? 0,
    runs: Array.isArray(s.history) ? s.history.length : 0,
    // 配置事实（不含敏感值，只说开关与数量）
    remote: input.cfg?.repo === '' ? null : input.cfg?.repo,
    branch: input.cfg?.branch ?? null,
    mirrorBranch: input.cfg?.mirrorBranch ?? null,
    secretGroups: Object.entries(input.cfg?.secretGroups ?? {}).filter(([, v]) => v === true).map(([k]) => k),
    sessionsEnabled: input.cfg?.syncSessions !== false,
    // 现场证据
    gitVersion: input.gitVersion ?? null,
    counts: input.counts ?? null,
    sessionFiles: input.sessionFiles ?? null,
    notes: input.notes ?? [],
  }
}

/**
 * 判断一份报告是否值得关注（供 UI/命令高亮）。
 * @param {object} report
 * @returns {string[]} 问题清单（空 = 健康）。
 */
export function reportIssues(report) {
  const out = []
  if (report?.state === 'error') out.push(`同步失败：${report.lastError?.code ?? '?'} ${report.lastError?.message ?? ''}`.trim())
  if (report?.remote === null) out.push('未配置远端仓库')
  if (report?.gitVersion === null) out.push('git 不可用（未检测到版本）')
  if ((report?.backoffUntil ?? 0) > Date.now()) out.push(`处于退避中（至 ${new Date(report.backoffUntil).toISOString()}）`)
  if ((report?.counts?.files ?? 0) === 0) out.push('本机没有可同步的文件（注册表未命中）')
  return out
}

/**
 * 采集 / 落盘 / 回读体检报告（渲染是下面的纯函数）。
 * 报告写进本机 `omnisync-devices/<deviceId>.json`，随同步上云 —— 这是看
 * "另一台机器怎么了"的唯一窗口，所以采集与渲染分家，采集留在这里。
 * @param {object} deps - { state, cfg, fsDeps, version, sectionOf, runGit }。
 */
export function makeHealth(deps) {
  const gitVersion = async () => {
    try {
      const r = await deps.runGit(['--version'])
      return r.code === 0 ? String(r.stdout).trim() : null
    } catch { return null }
  }
  const collect = async (extra = {}) => {
    const s = await deps.state()
    const files = await deps.fsDeps.listLocal('').catch(() => [])
    return buildReport({
      deviceId: s.deviceId, version: deps.version, state: s, cfg: deps.cfg,
      gitVersion: await gitVersion(),
      counts: { files: files.length, classified: files.filter((f) => deps.sectionOf(f.rel) !== null).length },
      sessionFiles: files.filter((f) => f.rel.startsWith('sessions/')).length,
      ...extra,
    })
  }
  return {
    collect,
    write: async (extra = {}) => {
      const report = await collect(extra)
      await deps.fsDeps.writeLocal(`omnisync-devices/${report.deviceId}.json`,
        Buffer.from(JSON.stringify(report, null, 2) + '\n', 'utf8'), { mode: 0o644 })
      return report
    },
    readAll: async () => {
      const out = []
      for (const f of await deps.fsDeps.listLocal('omnisync-devices')) {
        const raw = await deps.fsDeps.readLocal(f.rel)
        if (raw === null) continue
        try { out.push(JSON.parse(raw.toString('utf8'))) } catch { /* 损坏报告忽略 */ }
      }
      return out.sort((a, b) => (b.at ?? 0) - (a.at ?? 0))
    },
  }
}

/**
 * 渲染 doctor 文本（本机 + 其他机器的报告）。
 * @param {() => Promise<object>} writeMine - 生成并落盘本机报告。
 * @param {() => Promise<object[]>} readAll - 读取全部机器报告。
 * @returns {Promise<string>} 人读文本。
 */
export async function doctorText(writeMine, readAll) {
  const mine = await writeMine({ notes: ['generated by /omnisync doctor'] })
  const lines = ['omnisync doctor', '', '── 本机 ──']
  for (const [k, v] of Object.entries(mine)) {
    if (k === 'notes') continue
    lines.push(`  ${k.padEnd(16)} ${typeof v === 'object' && v !== null ? JSON.stringify(v) : String(v)}`)
  }
  const issues = reportIssues(mine)
  lines.push('', issues.length === 0 ? '  ✓ 本机未发现问题' : `  ⚠ ${issues.length} 个问题：`)
  for (const i of issues) lines.push(`    - ${i}`)

  const others = (await readAll()).filter((r) => r.deviceId !== mine.deviceId)
  if (others.length === 0) {
    lines.push('', '（暂无其他机器的报告 —— 另一台推送后即可看到）')
  } else {
    lines.push('', `── 其他机器（${others.length}）──`)
    for (const r of others) {
      const bad = reportIssues(r)
      lines.push(`  ${r.deviceId} · v${r.version} · ${r.platform}/${r.arch} · ${bad.length === 0 ? '健康' : `${bad.length} 个问题`}`)
      for (const i of bad) lines.push(`    - ${i}`)
    }
  }
  return lines.join('\n')
}
